# Hadolint configuration file

failure-threshold: info
strict-labels: false

# configure ignore rules
# see https://github.com/hadolint/hadolint#rules for a list of available rules.
ignored:
  - DL3016
  - DL3018
