---
name: Dev-Workflow

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yml

  call-release-tst-workflow:
    uses: ./.github/workflows/release-tst.yml
    secrets: inherit

  call-container-build-workflow:
    needs:
      - call-ci-workflow
    uses: ./.github/workflows/build-container.yml
    with:
      container-tag: dev
    secrets: inherit
