---
name: Main-Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yml

  call-release-tst-workflow:
    uses: ./.github/workflows/release-tst.yml
    secrets: inherit

  call-release-workflow:
    needs:
      - call-ci-workflow
      - call-release-tst-workflow
    uses: ./.github/workflows/release.yml
    secrets: inherit
